name = "74163"
title = "CD74HCT163"
dip = 16
width = 300
1 = "#MR"
2 = "CP"
3 = "P0"
4 = "P1"
5 = "P2"
6 = "P3"
7 = "PE"
8 = "GND"
9 = "#SPE"
10 = "TE"
11 = "Q3"
12 = "Q2"
13 = "Q1"
14 = "Q0"
15 = "TC"
16 = "Vcc"
