# MC68HC11D0 DIP definition
# https://github.com/tgtakaoka/dip
name = "MC68HC11D0"
title = "MC68HC11D0 Mode3"
dip = 40
width = 600
1 = "VSS"
2 = "AD0"
3 = "AD1"
4 = "AD2"
5 = "AD3"
6 = "AD4"
7 = "AD5"
8 = "AD6"
9 = "AD7"
10 = "#XIRQ"
11 = "R/W"
12 = "AS"
13 = "#RESET"
14 = "#IRQ"
15 = "PD0, RxD"
16 = "PD1, TxD"
17 = "PD2, MISO"
18 = "PD3, MOSI"
19 = "PD4, SCK"
20 = "PD5, #SS"
21 = "VDD"
22 = "PA7"
23 = "PA5"
24 = "PA3"
25 = "PA2"
26 = "PA1"
27 = "PA0"
28 = "A8"
29 = "A9"
30 = "A10"
31 = "A11"
32 = "A12"
33 = "A13"
34 = "A14"
35 = "A15"
36 = "MODB"
37 = "MODA, #LIR"
38 = "E"
39 = "EXTAL"
40 = "XTAL"
