# N80186 PLCC definition
# https://github.com/tgtakaoka/dip
name = "N80186"
title = "N80186"
qfj = 68
pin1 = "left-top"
 1 = ""
 2 = ""
 3 = ""
 4 = ""
 5 = ""
 6 = ""
 7 = ""
 8 = ""
 9 = "VCC"
10 = ""
11 = ""
12 = ""
13 = ""
14 = ""
15 = ""
16 = ""
17 = ""
18 = "DRQ0"
19 = "DRQ1"
20 = "TMRIN0"
21 = "TMRIN1"
22 = "TMROUT0"
23 = "TMROUT1"
24 = "#RES"
25 = ""
26 = "VSS"
27 = ""
28 = ""
29 = ""
30 = ""
31 = ""
32 = ""
33 = ""
34 = ""
35 = ""
36 = ""
37 = ""
38 = ""
39 = ""
40 = ""
41 = "INT3, #INTA1, IRQ"
42 = "INT2, #INTA0"
43 = "VCC"
44 = "INT1, #SELECT"
45 = "INT0"
46 = "NMI"
47 = "#TEST"
48 = ""
49 = ""
50 = ""
51 = ""
52 = ""
53 = ""
55 = ""
56 = "CLKOUT"
57 = "RESET"
58 = "X2"
59 = "X1"
60 = ""
61 = ""
62 = ""
63 = ""
65 = ""
66 = ""
67 = ""
68 = ""
