# N80186 PLCC definition
# https://github.com/tgtakaoka/dip
name = "N80186"
title = "N80186"
plcc = 68
pin1 = "left-top"
 1 = "AD15"
 2 = "AD7"
 3 = "AD14"
 4 = "AD6"
 5 = "AD13"
 6 = "AD5"
 7 = "AD12"
 8 = "AD4"
 9 = "VCC"
10 = "AD10"
11 = "AD3"
12 = "AD10"
13 = "AD2"
14 = "AD9"
15 = "AD1"
16 = "AD8"
17 = "AD0"
18 = "DRQ0"
19 = "DRQ1"
20 = "TMRIN0"
21 = "TMRIN1"
22 = "TMROUT0"
23 = "TMROUT1"
24 = "#RES"
25 = "#PCS0"
26 = "VSS"
27 = "#PCS1"
28 = "#PCS2"
29 = "#PCS3"
30 = "#PCS4"
31 = "#PCS5, A1"
32 = "#PCS6, A2"
33 = "#LCS"
34 = "#UCS"
35 = "#MCS3"
36 = "#MCS2"
37 = "#MCS1"
38 = "#MCS0"
39 = "#DEN"
40 = "DT/#R"
41 = "INT3, #INTA1, IRQ"
42 = "INT2, #INTA0"
43 = "VCC"
44 = "INT1, #SELECT"
45 = "INT0"
46 = "NMI"
47 = "#TEST, BUSY"
48 = "#LOCK"
49 = "SRDY"
50 = "HOLD"
51 = "HLDA"
52 = "#S0"
53 = "#S1"
54 = "#S2"
55 = "ARDY"
56 = "CLKOUT"
57 = "RESET"
58 = "X2"
59 = "X1"
60 = "VSS"
61 = "ALE, QS0"
62 = "#RD, #QSMD"
63 = "#WR, QS1"
64 = "#BHE"
65 = "A19, S6"
66 = "A18, S5"
67 = "A17, S4"
68 = "A16, S3"
