# N80C187 PLCC definition
# https://github.com/tgtakaoka/dip
name = "N80C187"
title = "N80C187"
qfj = 44
pin1 = "top-center"
 1 = "VCC"
 2 = "VSS"
 3 = "VCC"
 4 = "VSS"
 5 = "D15"
 6 = "(nc)"
 7 = "D14"
 8 = "D13"
 9 = "D12"
10 = "VCC"
11 = "(nc)"
12 = "VSS"
13 = "D11"
14 = "D10"
15 = "VCC"
16 = "D9"
17 = "D8"
18 = "D7"
19 = "D6"
20 = "D5"
21 = "D4"
22 = "D3"
23 = "(nc)"
24 = "D2"
25 = "D1"
26 = "D0"
27 = "PEREQ"
28 = "BUSY"
29 = "#ERROR"
30 = "#NPRD"
31 = "#NPWR"
32 = "CMD0"
33 = "(nc)"
34 = "VSS"
35 = "CMD1"
36 = "CLK"
37 = "NPS2"
38 = "#NPS1"
39 = "RESET"
40 = "(nc)"
41 = "VSS"
42 = "VCC"
43 = "VSS"
44 = "CKM"
