# NG880386SX BQFP definition
# https://github.com/tgtakaoka/dip
name = "386SX"
title = "NG80386SX"
bqfp=100
pin1 = "left-top"
 1 = "D0"
 2 = "VSS"
 3 = "HDLA"
 4 = "HOLD"
 5 = "VSS"
 6 = "#NA"
 7 = "#READY"
 8 = "VCC"
 9 = "VCC"
10 = "VCC"
11 = "VSS"
12 = "VSS"
13 = "VSS"
14 = "VSS"
15 = "CLK2"
16 = "#ADS"
17 = "#BLE"
18 = "A1"
19 = "#BHE"
20 = "(nc)"
21 = "VCC"
22 = "VSS"
23 = "M/#IO"
24 = "D/#C"
25 = "W/#R"
26 = "#LOCK"
27 = "(nc)"
28 = "#FLT"
29 = "(nc)"
30 = "(nc)"
31 = "(nc)"
32 = "VCC"
33 = "#RESET"
34 = "#BUSY"
35 = "VSS"
36 = "#ERROR"
37 = "PEREQ"
38 = "NMI"
39 = "VCC"
40 = "INTR"
41 = "VSS"
42 = "VCC"
43 = "(nc)"
44 = "(nc)"
45 = "(nc)"
46 = "(nc)"
47 = "(nc)"
48 = "VCC"
49 = "VSS"
50 = "VSS"
51 = "A2"
52 = "A3"
53 = "A4"
54 = "A5"
55 = "A6"
56 = "A7"
57 = "VCC"
58 = "A8"
59 = "A9"
60 = "A10"
61 = "A11"
62 = "A12"
63 = "VSS"
64 = "A13"
65 = "A14"
66 = "A15"
67 = "VSS"
68 = "VSS"
69 = "VCC"
70 = "A16"
71 = "VCC"
72 = "A17"
73 = "A18"
74 = "A19"
75 = "A20"
76 = "A21"
77 = "VSS"
78 = "VSS"
79 = "A22"
80 = "A23"
81 = "D15"
82 = "D14"
83 = "D13"
84 = "VCC"
85 = "VSS"
86 = "D12"
87 = "D11"
88 = "D10"
89 = "D9"
90 = "D8"
91 = "VCC"
92 = "D7"
93 = "D6"
94 = "D5"
95 = "D4"
96 = "D3"
97 = "VCC"
98 = "VSS"
99 = "D2"
100 = "D1"
